### PR TITLE
Add Louisiana Game Developers group

### PR DESCRIPTION
**Pull request by ngscheurich**
This adds a markdown entry and logo for LAGD.

There is no whitespace prescribed to exist around logo images on the home page. The existing groups' icons include whitespace as part of the image so they look okay, but I don't think built-in image padding is a common pattern.

Should we add padding to the template (which seems most compatible) or should I add a new version of my logo that includes it?

### CODE REVIEW

**Comment by williamadba** [comment]
about 25 minutes ago i merged in some additional metadata for groups, check out the examples of the three existing groups.

**Comment by ngscheurich** [comment]
@williamadba Hmm… I'm not sure I follow—was that in response to my question about the logo whitespace? I went ahead and rebased onto master and added `group_url` and `topics` to my entry in any case—thanks for the heads-up about that.

**Comment by williamadba** [comment]
right, sorry, not about the image whitespace question, more of a heads up to the recent change to the pattern for group files. Once we're settled on that and have the pages for the groups in place, I was going to fill up the list of groups from http://www.brssug.org/useful-links for starters.

**Comment by ngscheurich** [comment]
> right, sorry, not about the image whitespace question

No worries! I'll wait and see what I should do about the logo. Thanks again for the heads-up.

**Comment by james-alt** [comment]
@ngscheurich I think the padding to the template sounds reasonable. I have a feeling that template is going to change a lot and I'd rather not "fix" images to fit my bad design choices that may or may not shame some of our designer friends into helping out 😉

**Pull request merged**
