### PR TITLE
Resolves Issue #6 - CSS Setup

### PR DESCRIPTION
**Pull request by QuintonJason**
#### In this PR
- restructuring CSS folder structure

### CODE REVIEW

**Comment by QuintonJason** [comment]
@ngscheurich I've added post-css but need some assistance adding some of the postCSS plugins:
Can you assist me with this?
postcss-nested,
postcss-custom-properties,
autoprefixer?

**Comment by ngscheurich** [comment]
@QuintonJason Sure thing. Also, looks like the build is failing (missing PostCSS config?)—I'll take a look.

**Comment by ngscheurich** [comment]
@QuintonJason Okay, have a look-see. I've added the plugins you requested, and adding the config file removes the NPM error that was causing the build to fail. I didn't configure the plugins at all, but feel free to do so (or hit me up if you need assistance)!

Also, just in case you didn't know: GitHub now supports [drafts](https://github.blog/2019-02-14-introducing-draft-pull-requests/) for WIP PRs. 🙂

**Comment by QuintonJason** [comment]
@ngscheurich @james-alt  PR ready for review

**Pull request merged**
